-- AlterTable
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "nextBillingAt" TIMESTAMP(3);
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "referralBonusApplied" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "promoCodeUsed" TEXT;
