-- BRAND taxonomy + store claim token for draft/association flow

DO $$ BEGIN
  ALTER TYPE "StoreCategory" ADD VALUE IF NOT EXISTS 'BRAND';
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'BEVERAGE';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'ALCOHOL';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'SNACKS';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'PACKAGED_FOOD';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'COFFEE_TEA';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'DAIRY';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'PERSONAL_CARE';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'COSMETICS';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'FASHION';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'SPORTS';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'TECH';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'HOME_CARE';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'PETS';
ALTER TYPE "StoreSubcategory" ADD VALUE IF NOT EXISTS 'OTHER_BRAND';

ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'BEVERAGE_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'ALCOHOL_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'SNACKS_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'PACKAGED_FOOD_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'COFFEE_TEA_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'DAIRY_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'PERSONAL_CARE_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'COSMETICS_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'FASHION_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'SPORTS_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'TECH_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'HOME_CARE_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'PETS_GENERIC';
ALTER TYPE "StoreSegment" ADD VALUE IF NOT EXISTS 'OTHER_BRAND_GENERIC';

ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "claimToken" TEXT;
ALTER TABLE "Store" ADD COLUMN IF NOT EXISTS "claimTokenCreatedAt" TIMESTAMP(3);

CREATE UNIQUE INDEX IF NOT EXISTS "Store_claimToken_key" ON "Store"("claimToken");
