/** Campos de Store seguros para respuestas públicas y hidratación de pases. */
export const storePublicSelect = {
  id: true,
  name: true,
  slug: true,
  category: true,
  subcategory: true,
  segment: true,
  googlePlaceId: true,
  googleRating: true,
  googleReviewCount: true,
  googleRatingUpdatedAt: true,
  address: true,
  planType: true,
  billingStatus: true,
  billingPeriod: true,
  nextBillingAt: true,
  nextUsageBillingAt: true,
  whatsappUsed: true,
  maxStamps: true,
  currency: true,
  ondaValue: true,
  lat: true,
  lng: true,
  ownerName: true,
  ownerEmail: true,
  referralCode: true,
  freeMonthsBalance: true,
  referralBonusApplied: true,
  promoCodeUsed: true,
  referredByStoreId: true,
  createdAt: true,
  passDesign: true,
  promotions: true,
} as const;

export const storePassHydrateSelect = {
  ...storePublicSelect,
} as const;
